name: Release
on: push
#  push:
#    tags:
#      - '*'

jobs:
  publish:
    strategy:
      matrix:
        #os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Resolve Version
        id: preprocess
        run: |
          echo "${{ github.event.head_commit.message }}"
          echo "${TAG}"
          echo "${TAG#v}"
          echo "${TAG:1}"
        env:
          TAG: ${{ github.event.head_commit.message }}

      - name: install clarity dependencies
        working-directory: ./zedd-clarity
        run: |
          echo ${TAG}
          npm install
      - name: build clarity
        working-directory: ./zedd-clarity
        run: npm run build

      - name: install app dependencies
        working-directory: ./zedd-app
        run: npm install
      - name: generate icons
        working-directory: ./zedd-app
        run: npm run genicons
      - name: build release
        working-directory: ./zedd-app
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          #tag_name: ${{ github.ref }}
          #name: ${{ github.ref }}
          tag_name: 0.0.2-beta
          name: 0.0.2-beta
          draft: true
          files: |
            ./zedd-app/out/**/*.snap
            ./zedd-app/out/**/*.dmg
            ./zedd-app/out/make/squirrel.windows/x64/*.exe
            ./zedd-app/out/make/squirrel.windows/x64/*${{ steps.preprocess.outputs.version }}*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
